- name: Download Calico Manifest
  get_url:
    url: https://docs.projectcalico.org/v{{ calico_version }}/manifests/calico.yaml
    dest: /tmp

- name: Uncomment Pod CIDR parameter name
  replace:
    path: /tmp/calico.yaml
    regexp:  '# - name: CALICO_IPV4POOL_CIDR'
    replace: '- name: CALICO_IPV4POOL_CIDR'

- name: Uncommetn and replace Pod CIDR parameter value
  replace:
    path: /tmp/calico.yaml
    regexp:  '#   value: "192.168.0.0/16"'
    replace: '  value: "{{ pod_network_cidr }}"'

- name: Replace Calico image
  replace:
    path: /tmp/calico.yaml
    regexp: 'image: calico'
    replace: 'image: {{ container_local_repos[1] }}/calico'

- name: Install Calico
  become: yes
  become_user: "{{ k8s_admin }}"
  shell: kubectl apply -f /tmp/calico.yaml
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
