- name: Replace Ubuntu package repo
  replace:
    path: /etc/apt/sources.list
    regexp: '(?:[0-9a-zA-Z]{1,}[.]){1,}ubuntu.com'
    replace: '{{ ubuntu_local_package_repo }}'

- name: Install Containerd
  apt:
    name: containerd
    state: present
    update_cache: true

- name: Create Containerd Config Directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create Containderd certs.d Directory
  file:
    path: /etc/containerd/certs.d
    state: directory
    mode: '0755'

- name: Create Containerd local container repos directories
  file:
    path: "/etc/containerd/certs.d/{{ repo_item }}"
    state: directory
    mode: '0755'
  loop: "{{ container_local_repos }}"
  loop_control:
    loop_var: repo_item

- name: Copy Containerd Config File to Remote Hosts
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml

- name: Create Containerd local repos config files
  template:
    src: hosts.toml.j2
    dest: "/etc/containerd/certs.d/{{ repo_item }}/hosts.toml"
  loop: "{{ container_local_repos }}"
  loop_control:
    loop_var: repo_item

- name: Restart Containerd Service
  service:
    name: containerd
    state: restarted

- name: Install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Create apt-key folder
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Add Kubernetes apt-key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present

- name: Install kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true

- name: Install kubeadm
  apt:
    name: kubeadm
    state: present

- name: Install kubectl in Master Node
  apt:
    name: kubectl
    state: present
    force: yes
  when:
    - inventory_hostname in groups['master']
