- name: Bootstrap Debian
  import_tasks: bootstrap.yml
  tags:
    - bootstrap

- name: Install Dependencies on Debian
  import_tasks: install_depends_debian.yml
  when:
    - ansible_facts['os_family'] == "Debian"
  tags:
    - depends

- name: Install Dependencies on RedHat
  import_tasks: install_depends_redhat.yml
  when:
    - ansible_facts['os_family'] == "RedHat"
  tags:
    - depends

- name: HA
  import_tasks: ha.yml
  when:
    - inventory_hostname in groups['master']
  tags:
    - ha

- name: Initialize K8S Cluster
  import_tasks: init_cluster.yml
  when:
    - inventory_hostname in groups['init_master']
  tags:
    - init

- name: Master Tasks
  import_tasks: master.yml
  when:
    - inventory_hostname in groups['master']
  tags:
    - master

- name: Install Calico
  import_tasks: install_calico.yml
  when:
    - inventory_hostname in groups['init_master']
  tags:
    - calico

- name: Join Masters
  import_tasks: join_masters.yml
  tags:
    - join_masters

- name: Join Workers
  import_tasks: join_workers.yml
  tags:
    - join_workers
