- name: Bootstrap
  import_tasks: bootstrap.yml
  tags:
    - bootstrap

- name: Install Dependencies
  import_tasks: install-dependencies.yml
  tags:
    - depends

- name: HA
  import_tasks: ha.yml
  when:
    - inventory_hostname in groups['master']
  tags:
    - ha

- name: Initialize K8S Cluster
  import_tasks: init_cluster.yml
  when:
    - inventory_hostname in groups['init_master']
  tags:
    - init

- name: Master Tasks
  import_tasks: master.yml
  when:
    - inventory_hostname in groups['master']
  tags:
    - master

- name: Install Calico
  import_tasks: install_calico.yml
  when:
    - inventory_hostname in groups['init_master']
  tags:
    - calico

- name: Workers Tasks
  import_tasks: worker.yml
  tags:
    - worker
