- name: Create K8S Admin User
  user:
    name: "{{ k8s_admin }}"
    home: /home/{{ k8s_admin }}
    append: yes
    state: present
    shell: /bin/bash

- name: Create a dedicated sudo entry file for the K8S Admin
  file:
    path: "/etc/sudoers.d/{{ k8s_admin }}"
    state: touch
    mode: '0600'

- name: Setting up Sudo without Password for user "{{ k8s_admin }}"
  lineinfile:
    dest: "/etc/sudoers.d/{{ k8s_admin }}"
    line: '{{ k8s_admin }}  ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set authorized key for user copying it from current {{ k8s_admin }}  user.
  authorized_key:
    user: "{{ k8s_admin }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Create .kube directory
  become: yes
  become_user: "{{ k8s_admin }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /tmp/admin.conf
    dest: /home/{{ k8s_admin }}/.kube/config
    owner: "{{ k8s_admin }}"
